import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const $=(id)=>document.getElementById(id);const cfg=window.APP_CONFIG||{};const configured=/^https:\/\/.+\.supabase\.co$/.test(cfg.supabaseUrl||'')&&(cfg.supabasePublishableKey||'').length>20;const supabase=configured?createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true}}):null;
const state={session:null,profile:null,profiles:[],tasks:[],invitations:[],view:'all',channel:null};
const statusMap={todo:'Por iniciar',in_progress:'Em curso',review:'A validar',done:'Concluída'};const priorityMap={low:'Baixa',medium:'Média',high:'Alta',critical:'Crítica'};const columns=['todo','in_progress','review','done'];
function toast(message,error=false){const el=$('toast');el.textContent=message;el.className=`toast show${error?' error':''}`;clearTimeout(el._timer);el._timer=setTimeout(()=>el.className='toast',3200)}
function setMessage(id,text,success=false){const el=$(id);el.textContent=text||'';el.className=`form-message${success?' success':''}`}
function localDate(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Lisbon'}).format(new Date())}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function initials(value=''){return value.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase()||'?'}
function formatDate(date,time){if(!date)return'Sem prazo';return new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'2-digit',year:'numeric',...(time?{hour:'2-digit',minute:'2-digit'}:{})}).format(new Date(`${date}T${time||'12:00'}`))}
function isAdmin(){return state.profile?.role==='admin'&&state.profile?.active}
function profileName(id){const p=state.profiles.find(x=>x.id===id);return p?.full_name||p?.email||'Utilizador'}
function setBusy(text='A sincronizar…'){$('syncStatus').textContent=text}function setSynced(){$('syncStatus').textContent=`Sincronizado às ${new Intl.DateTimeFormat('pt-PT',{hour:'2-digit',minute:'2-digit'}).format(new Date())}`}
function applyTheme(theme){document.body.dataset.theme=theme;localStorage.setItem('team-theme',theme);$('themeLabel')&&($('themeLabel').textContent=theme==='light'?'Claro':'Escuro');document.querySelector('meta[name="theme-color"]').content=theme==='light'?'#f2f4f7':'#08090d'}
applyTheme(localStorage.getItem('team-theme')||'dark');
function showAuth(){$('loadingScreen').classList.add('hidden');$('appShell').classList.add('hidden');$('mobileTop').classList.add('hidden');$('loginScreen').classList.remove('hidden')}
function showApp(){$('loadingScreen').classList.add('hidden');$('loginScreen').classList.add('hidden');$('appShell').classList.remove('hidden');$('mobileTop').classList.remove('hidden')}
async function boot(){if(!configured){$('configWarning').classList.remove('hidden');showAuth();return}const{data:{session}}=await supabase.auth.getSession();session?await enterApp(session):showAuth()}
async function enterApp(session){state.session=session;const{data,error}=await supabase.from('profiles').select('*').eq('id',session.user.id).single();if(error||!data){await supabase.auth.signOut();showAuth();setMessage('loginMessage','Perfil não encontrado. Contacta o administrador.');return}if(!data.active){await supabase.auth.signOut();showAuth();setMessage('loginMessage','A tua conta está desativada. Contacta o diretor.');return}state.profile=data;$('userName').textContent=data.full_name||data.email;$('userRole').textContent=data.role==='admin'?'Administrador':data.department||'Colaborador';$('userAvatar').textContent=initials(data.full_name||data.email);document.querySelectorAll('.admin-only').forEach(el=>el.classList.toggle('hidden',!isAdmin()));showApp();await refreshData();subscribeRealtime()}
async function refreshData(){setBusy();const queries=[supabase.from('tasks').select('*').order('created_at',{ascending:false})];if(isAdmin())queries.push(supabase.from('profiles').select('*').order('full_name'),supabase.from('invitations').select('*').order('created_at',{ascending:false}));const results=await Promise.all(queries);const failed=results.find(r=>r.error);if(failed){toast(failed.error.message,true);setSynced();return}state.tasks=results[0].data||[];if(isAdmin()){state.profiles=results[1].data||[];state.invitations=results[2].data||[]}else state.profiles=[state.profile];populateFilters();render();setSynced()}
function subscribeRealtime(){if(state.channel)supabase.removeChannel(state.channel);state.channel=supabase.channel('team-control-live').on('postgres_changes',{event:'*',schema:'public',table:'tasks'},refreshData).on('postgres_changes',{event:'*',schema:'public',table:'profiles'},refreshData).on('postgres_changes',{event:'*',schema:'public',table:'invitations'},refreshData).subscribe(status=>{$('connectionDot').style.background=status==='SUBSCRIBED'?'var(--good)':'var(--warn)'})}
function populateFilters(){const active=state.profiles.filter(p=>p.active);$('personFilter').innerHTML='<option value="">Todos</option>'+active.map(p=>`<option value="${p.id}">${escapeHtml(p.full_name||p.email)}</option>`).join('');const assignable=active.filter(p=>p.role==='collaborator');$('taskPerson').innerHTML=assignable.map(p=>`<option value="${p.id}">${escapeHtml(p.full_name||p.email)}</option>`).join('')}
function filteredTasks(){const query=$('searchInput').value.trim().toLowerCase(),person=$('personFilter').value,priority=$('priorityFilter').value,today=localDate();return state.tasks.filter(t=>{const search=[t.title,t.notes,profileName(t.assignee_id),profileName(t.created_by)].join(' ').toLowerCase();if((query&&!search.includes(query))||(person&&t.assignee_id!==person)||(priority&&t.priority!==priority))return false;if(state.view==='today'&&t.due_date!==today)return false;if(state.view==='late'&&!(t.due_date&&t.due_date<today&&t.status!=='done'))return false;if(state.view==='critical'&&t.priority!=='critical')return false;if(state.view==='completed'&&t.status!=='done')return false;return true})}
function renderWorkloadAlert(){const box=$('workloadAlert');if(!isAdmin()){box.classList.add('hidden');return}const collaborators=state.profiles.filter(p=>p.active&&p.role==='collaborator');if(collaborators.length<2){box.classList.add('hidden');return}const loads=collaborators.map(p=>({p,count:state.tasks.filter(t=>t.assignee_id===p.id&&t.status!=='done').length})).sort((a,b)=>b.count-a.count);const leader=loads[0],others=loads.slice(1),avg=others.reduce((s,x)=>s+x.count,0)/others.length;const overloaded=leader.count>=4&&leader.count>=avg+2&&leader.count>=Math.max(1,avg*1.5);if(!overloaded){box.classList.add('hidden');return}box.innerHTML=`<strong>Alerta privado de distribuição</strong><br>${escapeHtml(leader.p.full_name||leader.p.email)} tem <strong>${leader.count} tarefas ativas</strong>; a média dos restantes é <strong>${avg.toFixed(1)}</strong>.`;box.classList.remove('hidden')}
function render(){const today=localDate(),all=state.tasks,active=all.filter(t=>t.status!=='done').length,dueToday=all.filter(t=>t.due_date===today&&t.status!=='done').length,late=all.filter(t=>t.due_date&&t.due_date<today&&t.status!=='done').length,done=all.filter(t=>t.status==='done').length;$('statActive').textContent=active;$('statToday').textContent=dueToday;$('statLate').textContent=late;$('statRate').textContent=`${all.length?Math.round(done/all.length*100):0}%`;$('navAll').textContent=all.length;$('navToday').textContent=dueToday;$('navLate').textContent=late;$('navCritical').textContent=all.filter(t=>t.priority==='critical'&&t.status!=='done').length;$('navCompleted').textContent=done;renderWorkloadAlert();const data=filteredTasks();$('board').innerHTML=columns.map(status=>{const list=data.filter(t=>t.status===status);return`<section class="column"><div class="column-head"><span>${statusMap[status]}</span><span>${list.length}</span></div><div class="column-body">${list.length?list.map(taskCard).join(''):'<div class="empty">Sem tarefas</div>'}</div></section>`}).join('');document.querySelectorAll('.task-card').forEach(card=>card.onclick=()=>openTask(card.dataset.id))}
function taskCard(t){const late=t.due_date&&t.due_date<localDate()&&t.status!=='done';return`<article class="task-card" data-id="${t.id}"><div class="task-title">${escapeHtml(t.title)}</div><div class="task-meta"><span class="tag ${t.priority}">${priorityMap[t.priority]}</span></div><div class="task-person">Atribuída a: ${escapeHtml(profileName(t.assignee_id))}</div><div class="task-due ${late?'late':''}">${formatDate(t.due_date,t.due_time)}</div></article>`}
function clearTaskForm(){['taskId','taskTitle','taskOwner','taskDate','taskTime','taskNotes'].forEach(id=>$(id).value='');$('taskPriority').value='medium';$('taskStatus').value='todo';$('attachmentList').innerHTML='';$('auditList').innerHTML='';$('attachmentsSection').classList.add('hidden');$('auditSection').classList.add('hidden');$('deleteTaskBtn').style.display='none'}
function lockTaskFields(locked){['taskTitle','taskPerson','taskPriority','taskDate','taskTime'].forEach(id=>$(id).disabled=locked);$('collaboratorNote').classList.toggle('hidden',!locked)}
function openNewTask(){clearTaskForm();lockTaskFields(false);$('taskDialogTitle').textContent='Nova tarefa';$('taskOwner').value=state.profile.full_name||state.profile.email;const first=state.profiles.find(p=>p.active&&p.role==='collaborator');if(first)$('taskPerson').value=first.id;else toast('Cria primeiro um colaborador ativo.',true);$('taskDialog').showModal()}
async function openTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;clearTaskForm();$('taskId').value=t.id;$('taskTitle').value=t.title||'';$('taskOwner').value=profileName(t.created_by);$('taskPriority').value=t.priority;$('taskStatus').value=t.status;$('taskDate').value=t.due_date||'';$('taskTime').value=(t.due_time||'').slice(0,5);$('taskNotes').value=t.notes||'';$('taskPerson').value=t.assignee_id;$('taskDialogTitle').textContent=t.title;lockTaskFields(!isAdmin());$('deleteTaskBtn').style.display=isAdmin()?'inline-block':'none';$('attachmentsSection').classList.remove('hidden');$('auditSection').classList.remove('hidden');$('taskDialog').showModal();await Promise.all([loadAttachments(id),loadAudit(id)])}
async function saveTask(){const id=$('taskId').value,title=$('taskTitle').value.trim(),assignee_id=$('taskPerson').value;if(!title||!assignee_id){toast('Preenche a tarefa e seleciona quem a vai receber.',true);return}const payload=isAdmin()?{title,assignee_id,priority:$('taskPriority').value,status:$('taskStatus').value,due_date:$('taskDate').value||null,due_time:$('taskTime').value||null,notes:$('taskNotes').value.trim()||null}:{status:$('taskStatus').value,notes:$('taskNotes').value.trim()||null};setBusy('A guardar…');const result=id?await supabase.from('tasks').update(payload).eq('id',id):await supabase.from('tasks').insert(payload);if(result.error){toast(result.error.message,true);setSynced();return}$('taskDialog').close();toast('Tarefa guardada.');await refreshData()}
async function deleteTask(){const id=$('taskId').value;if(!id||!confirm('Eliminar definitivamente esta tarefa?'))return;const{error}=await supabase.from('tasks').delete().eq('id',id);if(error){toast(error.message,true);return}$('taskDialog').close();toast('Tarefa eliminada.');await refreshData()}
async function loadAttachments(taskId){const{data,error}=await supabase.from('task_attachments').select('*').eq('task_id',taskId).order('created_at',{ascending:false});if(error)return;$('attachmentList').innerHTML=(data||[]).length?data.map(a=>`<div class="attachment-item"><button class="btn small" data-path="${escapeHtml(a.storage_path)}">Abrir</button> ${escapeHtml(a.file_name)} <small>${Math.round((a.file_size||0)/1024)} KB</small></div>`).join(''):'<div class="empty">Sem anexos</div>';$('attachmentList').querySelectorAll('button').forEach(button=>button.onclick=async()=>{const{data:signed,error:signError}=await supabase.storage.from('task-evidence').createSignedUrl(button.dataset.path,60);if(signError){toast(signError.message,true);return}window.open(signed.signedUrl,'_blank','noopener')})}
async function uploadAttachment(){const taskId=$('taskId').value,file=$('attachmentFile').files[0];if(!taskId||!file){toast('Seleciona um ficheiro.',true);return}if(file.size>6291456){toast('O ficheiro excede 6 MB.',true);return}const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${taskId}/${crypto.randomUUID()}-${safe}`;setBusy('A carregar anexo…');let result=await supabase.storage.from('task-evidence').upload(path,file);if(result.error){setSynced();toast(result.error.message,true);return}result=await supabase.from('task_attachments').insert({task_id:taskId,file_name:file.name,storage_path:path,mime_type:file.type,file_size:file.size});if(result.error){setSynced();toast(result.error.message,true);return}$('attachmentFile').value='';toast('Anexo carregado.');await loadAttachments(taskId);setSynced()}
async function loadAudit(taskId){const{data,error}=await supabase.from('task_events').select('*').eq('task_id',taskId).order('created_at',{ascending:false});if(error)return;$('auditList').innerHTML=(data||[]).map(e=>`<div class="audit-item"><strong>${e.action==='created'?'Tarefa criada':'Tarefa atualizada'}</strong>${e.old_status!==e.new_status?` — ${e.old_status?statusMap[e.old_status]:'—'} → ${statusMap[e.new_status]}`:''}<br><small>${new Intl.DateTimeFormat('pt-PT',{dateStyle:'short',timeStyle:'short'}).format(new Date(e.created_at))}</small></div>`).join('')||'<div class="empty">Sem histórico</div>'}
async function updateProfile(id,changes){if(id===state.profile.id&&('active'in changes)&&!changes.active){toast('Não podes desativar a tua própria conta.',true);return}const{error}=await supabase.from('profiles').update(changes).eq('id',id);if(error){toast(error.message,true);return}toast('Acesso atualizado.');await openPeople()}
async function cancelInvite(id){if(!confirm('Cancelar este convite?'))return;const{error}=await supabase.from('invitations').delete().eq('id',id);if(error){toast(error.message,true);return}toast('Convite cancelado.');await openPeople()}
function copyInvite(email){const url=`${location.origin}/?invite=${encodeURIComponent(email)}`;navigator.clipboard.writeText(url).then(()=>toast('Link de ativação copiado.')).catch(()=>toast('Não foi possível copiar o link.',true))}
async function openPeople(){await refreshData();$('peopleList').innerHTML=state.profiles.map(p=>`<div class="person-row"><div><strong>${escapeHtml(p.full_name||p.email)}</strong><br><small>${escapeHtml(p.email)} · ${escapeHtml(p.department||'Sem departamento')}</small><br><span class="status-pill ${p.active?'':'inactive'}">${p.active?'Ativo':'Desativado'}</span></div><div class="person-actions"><select class="inline-select" data-role-user="${p.id}" ${p.id===state.profile.id?'disabled':''}><option value="collaborator" ${p.role==='collaborator'?'selected':''}>Colaborador</option><option value="admin" ${p.role==='admin'?'selected':''}>Administrador</option></select><button class="btn small" data-toggle-user="${p.id}" data-active="${!p.active}" ${p.id===state.profile.id?'disabled':''}>${p.active?'Desativar':'Ativar'}</button></div></div>`).join('')||'<div class="empty">Sem utilizadores</div>';$('peopleList').querySelectorAll('[data-toggle-user]').forEach(b=>b.onclick=()=>updateProfile(b.dataset.toggleUser,{active:b.dataset.active==='true'}));$('peopleList').querySelectorAll('[data-role-user]').forEach(s=>s.onchange=()=>updateProfile(s.dataset.roleUser,{role:s.value}));const pending=state.invitations.filter(i=>!i.accepted_at);$('inviteList').innerHTML=pending.map(i=>`<div class="person-row"><div><strong>${escapeHtml(i.full_name)}</strong><br><small>${escapeHtml(i.email)} · ${escapeHtml(i.department||'Sem departamento')} · ${i.role==='admin'?'Administrador':'Colaborador'}</small><br><span class="status-pill pending">Convite pendente</span></div><div class="person-actions"><button class="btn small" data-copy-email="${escapeHtml(i.email)}">Copiar link</button><button class="btn small danger" data-cancel-invite="${i.id}">Cancelar</button></div></div>`).join('')||'<div class="empty">Sem convites pendentes</div>';$('inviteList').querySelectorAll('[data-copy-email]').forEach(b=>b.onclick=()=>copyInvite(b.dataset.copyEmail));$('inviteList').querySelectorAll('[data-cancel-invite]').forEach(b=>b.onclick=()=>cancelInvite(b.dataset.cancelInvite))}
async function createInvite(){const email=$('inviteEmail').value.trim().toLowerCase(),full_name=$('inviteName').value.trim();if(!email||!full_name){toast('Preenche nome e email.',true);return}const{error}=await supabase.from('invitations').upsert({email,full_name,department:$('inviteDepartment').value.trim()||null,role:$('inviteRole').value,accepted_at:null},{onConflict:'email'});if(error){toast(error.message,true);return}['inviteEmail','inviteName','inviteDepartment'].forEach(id=>$(id).value='');toast('Email autorizado.');await openPeople()}
function teamMetrics(){const now=Date.now(),cutoff=now-30*86400000;return state.profiles.filter(p=>p.role==='collaborator').map(p=>{const tasks=state.tasks.filter(t=>t.assignee_id===p.id),active=tasks.filter(t=>t.status!=='done').length,late=tasks.filter(t=>t.status!=='done'&&t.due_date&&t.due_date<localDate()).length,completed30=tasks.filter(t=>t.status==='done'&&t.completed_at&&new Date(t.completed_at).getTime()>=cutoff).length,durations=tasks.filter(t=>t.status==='done'&&t.completed_at&&t.created_at).map(t=>(new Date(t.completed_at)-new Date(t.created_at))/86400000).filter(n=>n>=0);const avg=durations.length?durations.reduce((a,b)=>a+b,0)/durations.length:null;let health='Normal',cls='health-good';if(!p.active){health='Inativo';cls='health-bad'}else if(late>=3){health='Atenção';cls='health-bad'}else if(active>=8||late>0){health='Carga elevada';cls='health-warn'}return{p,active,late,completed30,avg,health,cls}})}
function openTeamDashboard(){const rows=teamMetrics();const totalActive=rows.reduce((s,r)=>s+r.active,0),totalLate=rows.reduce((s,r)=>s+r.late,0),top=[...rows].sort((a,b)=>b.completed30-a.completed30)[0];$('teamSummary').innerHTML=`<div class="summary-card"><span>Tarefas ativas</span><b>${totalActive}</b></div><div class="summary-card"><span>Em atraso</span><b>${totalLate}</b></div><div class="summary-card"><span>Mais conclusões em 30 dias</span><b>${top?escapeHtml(top.p.full_name||top.p.email):'—'}</b></div>`;$('teamMetricsBody').innerHTML=rows.map(r=>`<tr><td><strong>${escapeHtml(r.p.full_name||r.p.email)}</strong><br><small>${escapeHtml(r.p.department||'')}</small></td><td>${r.active}</td><td>${r.late}</td><td>${r.completed30}</td><td>${r.avg===null?'—':`${r.avg.toFixed(1)} dias`}</td><td class="${r.cls}">${r.health}</td></tr>`).join('')||'<tr><td colspan="6">Sem colaboradores.</td></tr>';$('teamDashboardDialog').showModal()}
function exportCsv(){const rows=[['Tarefa','Responsável','Atribuída a','Prioridade','Estado','Data limite','Hora','Observações'],...state.tasks.map(t=>[t.title,profileName(t.created_by),profileName(t.assignee_id),priorityMap[t.priority],statusMap[t.status],t.due_date||'',(t.due_time||'').slice(0,5),t.notes||''])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));link.download=`tarefas_${localDate()}.csv`;link.click();URL.revokeObjectURL(link.href)}
$('loginTab').onclick=()=>{$('loginPanel').classList.remove('hidden');$('registerPanel').classList.add('hidden');$('loginTab').classList.add('active');$('registerTab').classList.remove('active')};$('registerTab').onclick=()=>{$('registerPanel').classList.remove('hidden');$('loginPanel').classList.add('hidden');$('registerTab').classList.add('active');$('loginTab').classList.remove('active')};
$('loginBtn').onclick=async()=>{setMessage('loginMessage','');const{data,error}=await supabase.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error){setMessage('loginMessage',error.message);return}await enterApp(data.session)};
$('registerBtn').onclick=async()=>{const email=$('registerEmail').value.trim().toLowerCase(),password=$('registerPassword').value,full_name=$('registerName').value.trim();if(!email||!full_name){setMessage('registerMessage','Preenche nome e email.');return}if(password.length<8){setMessage('registerMessage','A palavra-passe deve ter pelo menos 8 caracteres.');return}const{data:invite,error:inviteError}=await supabase.rpc('is_email_invited',{candidate_email:email});if(inviteError){setMessage('registerMessage','Não foi possível validar o convite.');return}if(!invite){setMessage('registerMessage','Este email não foi autorizado pelo diretor.');return}const{error}=await supabase.auth.signUp({email,password,options:{data:{full_name}}});if(error){setMessage('registerMessage',error.message);return}setMessage('registerMessage','Conta criada. Confirma o email e depois entra.',true)};
$('addTaskBtn').onclick=openNewTask;$('mobileAddBtn').onclick=openNewTask;$('saveTaskBtn').onclick=saveTask;$('deleteTaskBtn').onclick=deleteTask;$('uploadAttachmentBtn').onclick=uploadAttachment;$('peopleBtn').onclick=()=>{$('peopleDialog').showModal();openPeople()};$('teamDashboardBtn').onclick=openTeamDashboard;$('refreshPeopleBtn').onclick=openPeople;$('createInviteBtn').onclick=createInvite;$('exportCsvBtn').onclick=exportCsv;$('refreshBtn').onclick=refreshData;$('logoutBtn').onclick=async()=>{await supabase.auth.signOut();location.reload()};$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');$('themeBtn').onclick=()=>applyTheme(document.body.dataset.theme==='light'?'dark':'light');
$('resetFiltersBtn').onclick=()=>{$('searchInput').value='';$('personFilter').value='';$('priorityFilter').value='';render()};['searchInput','personFilter','priorityFilter'].forEach(id=>{$(id).oninput=render;$(id).onchange=render});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('nav').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;$('nav').querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const labels={all:'Todas as tarefas',today:'Para hoje',late:'Em atraso',critical:'Críticas',completed:'Concluídas'};$('pageTitle').textContent=labels[state.view];$('sidebar').classList.remove('open');render()});
const inviteParam=new URLSearchParams(location.search).get('invite');if(inviteParam){$('registerEmail').value=inviteParam;$('registerTab').click()}
supabase?.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_IN'&&session&&!state.profile)await enterApp(session);if(event==='SIGNED_OUT')showAuth()});boot();