import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.APP_CONFIG||{};const supabase=createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);const state={session:null,profile:null,profiles:[],tasks:[],person:'all',filter:'active',view:'tasks'};
const statusLabel={todo:'Por iniciar',in_progress:'Em curso',review:'A validar',done:'Validada'};const priorityLabel={low:'Baixa',medium:'Média',high:'Alta',critical:'Crítica'};
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localDate=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Lisbon'}).format(new Date());
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2800)}
function show(id){['loading','login','app'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
function isAdmin(){return state.profile?.role==='admin'}
function profileName(id){const p=state.profiles.find(x=>x.id===id);return p?.full_name||p?.email||'Sem responsável'}
function formatDate(d,t){if(!d)return'Sem prazo';const day=d===localDate()?'Hoje':new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'short'}).format(new Date(`${d}T12:00`));return `${day}${t?` · ${t.slice(0,5)}`:''}`}
async function boot(){const{data:{session}}=await supabase.auth.getSession();if(!session)return show('login');await enter(session)}
async function enter(session){state.session=session;const{data,error}=await supabase.from('profiles').select('*').eq('id',session.user.id).single();if(error||!data?.active){await supabase.auth.signOut();$('loginError').textContent='Acesso indisponível.';return show('login')}state.profile=data;document.querySelectorAll('.admin-only').forEach(e=>e.classList.toggle('hidden',!isAdmin()));$('hello').textContent=`Olá, ${(data.full_name||data.email).split(' ')[0]}`;show('app');await refresh();subscribe()}
async function refresh(){const queries=[supabase.from('tasks').select('*').order('created_at',{ascending:false})];if(isAdmin())queries.push(supabase.from('profiles').select('*').order('full_name'));const results=await Promise.all(queries);if(results.some(r=>r.error))return toast('Erro ao sincronizar dados.');state.tasks=results[0].data||[];state.profiles=isAdmin()?(results[1].data||[]):[state.profile];render()}
function subscribe(){supabase.channel('atlas-v3-live').on('postgres_changes',{event:'*',schema:'public',table:'tasks'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'profiles'},refresh).subscribe()}
function filtered(){let list=state.tasks.filter(t=>isAdmin()||t.assignee_id===state.profile.id);if(state.person!=='all')list=list.filter(t=>t.assignee_id===state.person);const today=localDate();if(state.filter==='active')list=list.filter(t=>t.status!=='done');if(state.filter==='today')list=list.filter(t=>t.due_date===today&&t.status!=='done');if(state.filter==='late')list=list.filter(t=>t.due_date&&t.due_date<today&&t.status!=='done');if(state.filter==='critical')list=list.filter(t=>t.priority==='critical'&&t.status!=='done');if(state.filter==='review')list=list.filter(t=>t.status==='review');return list.sort((a,b)=>priorityScore(b.priority)-priorityScore(a.priority)||(a.due_date||'9999').localeCompare(b.due_date||'9999'))}
const priorityScore=p=>({critical:4,high:3,medium:2,low:1}[p]||0);
function render(){const own=state.tasks.filter(t=>isAdmin()||t.assignee_id===state.profile.id),active=own.filter(t=>t.status!=='done'),late=active.filter(t=>t.due_date&&t.due_date<localDate()),review=own.filter(t=>t.status==='review');$('statActive').textContent=active.length;$('statLate').textContent=late.length;$('statReview').textContent=review.length;$('navReview').textContent=review.length;renderTabs();renderTasks();renderPriority(active);renderTeam();renderReports();}
function renderTabs(){if(!isAdmin())return $('peopleTabs').innerHTML='';const people=state.profiles.filter(p=>p.role==='collaborator'&&p.active);const tabs=[{id:'all',name:'Todos',count:state.tasks.length},...people.map(p=>({id:p.id,name:p.full_name||p.email,count:state.tasks.filter(t=>t.assignee_id===p.id&&t.status!=='done').length}))];$('peopleTabs').innerHTML=tabs.map(t=>`<button class="${state.person===t.id?'active':''}" data-person="${t.id}">${esc(t.name)} (${t.count})</button>`).join('');$('peopleTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.person=b.dataset.person;renderTabs();renderTasks()})}
function card(t){return `<article class="task-card" data-id="${t.id}"><div><div class="task-title">${esc(t.title)}</div><div class="task-meta"><span class="pill ${t.priority}">${priorityLabel[t.priority]}</span><span class="pill ${t.status}">${statusLabel[t.status]}</span><span>${esc(profileName(t.assignee_id))}</span><span>${formatDate(t.due_date,t.due_time)}</span></div></div><span class="task-arrow">›</span></article>`}
function renderTasks(){const list=filtered();const labels={active:'Tarefas ativas',today:'Tarefas de hoje',late:'Tarefas em atraso',critical:'Tarefas críticas',review:'Pendentes de validação'};$('listTitle').textContent=labels[state.filter]||'Tarefas';$('taskList').innerHTML=list.map(card).join('')||'<div class="empty">Sem tarefas neste filtro.</div>';$('taskList').querySelectorAll('[data-id]').forEach(e=>e.onclick=()=>openTask(e.dataset.id));document.querySelectorAll('.quick-filters button').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.filter))}
function renderPriority(active){const list=[...active].sort((a,b)=>priorityScore(b.priority)-priorityScore(a.priority)||(a.due_date||'9999').localeCompare(b.due_date||'9999')).slice(0,3);$('prioritySection').classList.toggle('hidden',state.view!=='tasks'||!list.length);$('priorityList').innerHTML=list.map((t,i)=>`<article class="priority-item" data-id="${t.id}"><div><div class="task-title">${i+1}. ${esc(t.title)}</div><div class="task-meta"><span>${esc(profileName(t.assignee_id))}</span><span>${formatDate(t.due_date,t.due_time)}</span></div></div><span class="pill ${t.priority}">${priorityLabel[t.priority]}</span></article>`).join('');$('priorityList').querySelectorAll('[data-id]').forEach(e=>e.onclick=()=>openTask(e.dataset.id))}
function renderTeam(){if(!isAdmin())return;const people=state.profiles.filter(p=>p.role==='collaborator');$('teamList').innerHTML=people.map(p=>{const active=state.tasks.filter(t=>t.assignee_id===p.id&&t.status!=='done').length,late=state.tasks.filter(t=>t.assignee_id===p.id&&t.status!=='done'&&t.due_date&&t.due_date<localDate()).length;return `<article class="team-card"><span>${esc(p.full_name||p.email)}</span><b>${active}</b><small>Tarefas ativas · ${late} em atraso</small></article>`}).join('')||'<div class="empty">Sem colaboradores.</div>'}
function renderReports(){if(!isAdmin())return;const done=state.tasks.filter(t=>t.status==='done').length,rate=state.tasks.length?Math.round(done/state.tasks.length*100):0;$('reportCards').innerHTML=`<div><span>Total de tarefas</span><b>${state.tasks.length}</b></div><div><span>Concluídas</span><b>${done}</b></div><div><span>Taxa de conclusão</span><b>${rate}%</b></div>`}
function setView(view){state.view=view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('stats').classList.toggle('hidden',view==='team'||view==='reports');$('prioritySection').classList.toggle('hidden',view!=='tasks');$('teamView').classList.toggle('hidden',view!=='team');$('reportsView').classList.toggle('hidden',view!=='reports');$('peopleTabs').parentElement.classList.toggle('hidden',view==='team'||view==='reports');if(view==='validations'){state.filter='review';renderTasks()}else if(view==='tasks'&&state.filter==='review'){state.filter='active';renderTasks()}}
function resetForm(){$('taskId').value='';$('taskTitle').value='';$('taskPriority').value='medium';$('taskStatus').value='todo';$('taskDate').value='';$('taskTime').value='';$('taskNotes').value='';$('deleteBtn').classList.add('hidden');$('dialogTitle').textContent='Nova tarefa'}
function populatePeople(){const active=state.profiles.filter(p=>p.active&&(p.role==='collaborator'||!isAdmin()));$('taskPerson').innerHTML=active.map(p=>`<option value="${p.id}">${esc(p.full_name||p.email)}</option>`).join('')}
function openNew(){resetForm();populatePeople();if(!isAdmin())$('taskPerson').value=state.profile.id;$('taskDialog').showModal()}
function openTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;resetForm();populatePeople();$('taskId').value=t.id;$('taskTitle').value=t.title||'';$('taskPerson').value=t.assignee_id||'';$('taskPriority').value=t.priority||'medium';$('taskStatus').value=t.status||'todo';$('taskDate').value=t.due_date||'';$('taskTime').value=(t.due_time||'').slice(0,5);$('taskNotes').value=t.notes||'';$('dialogTitle').textContent=t.title;$('deleteBtn').classList.toggle('hidden',!isAdmin());['taskTitle','taskPerson','taskPriority','taskDate','taskTime'].forEach(id=>$(id).disabled=!isAdmin());$('taskDialog').showModal()}
async function saveTask(){const id=$('taskId').value,payload=isAdmin()?{title:$('taskTitle').value.trim(),assignee_id:$('taskPerson').value,priority:$('taskPriority').value,status:$('taskStatus').value,due_date:$('taskDate').value||null,due_time:$('taskTime').value||null,notes:$('taskNotes').value.trim()||null}:{status:$('taskStatus').value,notes:$('taskNotes').value.trim()||null};if(!payload.title&&isAdmin())return toast('Indica o nome da tarefa.');const result=id?await supabase.from('tasks').update(payload).eq('id',id):await supabase.from('tasks').insert(payload);if(result.error)return toast(result.error.message);$('taskDialog').close();toast('Tarefa guardada.');await refresh()}
async function deleteTask(){const id=$('taskId').value;if(!id||!confirm('Eliminar definitivamente esta tarefa?'))return;const{error}=await supabase.from('tasks').delete().eq('id',id);if(error)return toast(error.message);$('taskDialog').close();toast('Tarefa eliminada.');await refresh()}
function exportCsv(){const rows=[['Tarefa','Responsável','Prioridade','Estado','Data','Hora'],...state.tasks.map(t=>[t.title,profileName(t.assignee_id),priorityLabel[t.priority],statusLabel[t.status],t.due_date||'',(t.due_time||'').slice(0,5)])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download=`atlas_${localDate()}.csv`;a.click();URL.revokeObjectURL(a.href)}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';const{data,error}=await supabase.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return $('loginError').textContent='Email ou palavra-passe incorretos.';await enter(data.session)};
$('newTaskBtn').onclick=openNew;$('taskForm').onsubmit=e=>{e.preventDefault();saveTask()};$('deleteBtn').onclick=deleteTask;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('taskDialog').close());document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;state.view=state.filter==='review'?'validations':'tasks';setView(state.view);renderTasks()});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('atlas-theme',document.body.classList.contains('dark')?'dark':'light')};$('logoutBtn').onclick=async()=>{await supabase.auth.signOut();location.reload()};$('openPeopleBtn').onclick=()=>location.href='../';$('exportBtn').onclick=exportCsv;if(localStorage.getItem('atlas-theme')==='dark')document.body.classList.add('dark');boot();